#! /bin/bash
echo -e "$BG_1$FONT_COLOR_1"HOSTNAME'\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$(hostname)$ENDCOLOR"
TIMEZONE="$(timedatectl | awk '/zone/ {print $3, "UTC", $5/100}')"
echo -e "$BG_1$FONT_COLOR_1"TIMEZONE'\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$TIMEZONE$ENDCOLOR"
echo -e "$BG_1$FONT_COLOR_1"USER'\t\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$USER$ENDCOLOR"
OS="$(awk '{print $1, $2, $3}' /etc/issue | head -1)"
echo -e "$BG_1$FONT_COLOR_1"OS'\t\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$OS$ENDCOLOR"
echo -e "$BG_1$FONT_COLOR_1"DATE'\t\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$(date +"%d %b %Y %T")$ENDCOLOR"
UPTIME="$(uptime | awk '{print $0}')"
#echo -e "$BG_1$FONT_COLOR_1"UPTIME'\t\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$(uptime)$ENDCOLOR"
echo -e "$BG_1$FONT_COLOR_1"UPTIME'\t\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$UPTIME$ENDCOLOR"
UPTIME_SEC="$(awk '{print $1}' /proc/uptime)"
echo -e "$BG_1$FONT_COLOR_1"UPTIME_SEC'\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$UPTIME_SEC$ENDCOLOR"
IP="$(hostname -I | awk '{print $1}')"
echo -e "$BG_1$FONT_COLOR_1"IP'\t\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$IP$ENDCOLOR"
 # MASK="$(ifconfig | awk '/broadcast/{print $4}' | head -1)"
 # echo -e "$BG_1$FONT_COLOR_1"MASK'\t\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$MASK$ENDCOLOR"
GATEWAY="$(ip r | awk '/default/{print $3}')"
. ./network.sh
echo -e "$BG_1$FONT_COLOR_1"GATEWAY'\t\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$GATEWAY$ENDCOLOR"
RAM_TOTAL="$(free -m | awk '/Mem/{printf "%.3fGb", $2/1024}')"
echo -e "$BG_1$FONT_COLOR_1"RAM_TOTAL'\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$RAM_TOTAL$ENDCOLOR"
RAM_USED="$(free -m | awk '/Mem/{printf "%.3fGb", $3/1024}')"
echo -e "$BG_1$FONT_COLOR_1"RAM_USED'\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$RAM_USED$ENDCOLOR"
RAM_FREE="$(free -m | awk '/Mem/{printf "%.3fGb", $3/1024}')"
echo -e "$BG_1$FONT_COLOR_1"RAM_FREE'\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$RAM_FREE$ENDCOLOR"
SPACE_ROOT="$(df -kT /root/ | awk '/ubuntu/{printf "%.2fMb\n", $3/1024}')"
echo -e "$BG_1$FONT_COLOR_1"SPACE_ROOT'\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$SPACE_ROOT$ENDCOLOR"
SPACE_ROOT_USED="$(df -kT /root/ | awk '/ubuntu/{printf "%.2fMb\n", $4/1024}')"
echo -e "$BG_1$FONT_COLOR_1"SPACE_ROOT_USED'\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$SPACE_ROOT_USED$ENDCOLOR"
SPACE_ROOT_FREE="$(df -kT /root/ | awk '/ubuntu/{printf "%.2fMb\n", $5/1024}')"
echo -e "$BG_1$FONT_COLOR_1"SPACE_ROOT_FREE'\t'"$ENDCOLOR" = "$BG_2$FONT_COLOR_2$SPACE_ROOT_FREE$ENDCOLOR"

